### PR TITLE
implement lexicographic navigation

### PR DESCRIPTION
**Pull request by OrkWard**
preview the build at https://orkward.github.io/mirror-front

### CODE REVIEW

**Comment by RalXYZ** [comment]
6，牛逼

**Comment by OrkWard** [comment]
虽然 index.jsx 看起来改了很多其实只是不小心缩进的原因导致（
我应该只在最后面添加一个新的 component 然后把整个用 `<></>` 包起来（毕竟不能直接 return 多个并列标签）

**Comment by RalXYZ** [comment]
@OrkWard I have reviewed this pull request and completed all the comments. If you have better suggestions regarding the comments, we can continue the discussion.

**Comment by wfwf1997** [comment]
I suppose hash navigation is totally fine. It's simple but even works in lazy loading case. Actually, it is a quite common practice to use hash for quick navigation in a long articles. The url with hash can also make people who open the link jump to the target paragraph faster. React will not trigger re-rendering when the hash changes by default. And if you're really concerned with the history, just use `history.replaceState`. But for me, I don't mind the change.

**Comment by wfwf1997** [comment]
@RalXYZ I suppose we could also add hash for each mirror card!

**Comment by OrkWard** [comment]
Glad to heard that, I don't mean to pursue perfect either, just merge it if no other problem

Also it won't be busy in my 4th year, so if need I can participate in maintainance

**Comment by RalXYZ** [comment]
> Also it won't be busy in my 4th year, so if need I can participate in maintainance

Thank you very much! We really appreciate your contribution, but we don't want to burden you with too much work. After all, contributing to open-source communities may not bring you material benefits or provide significant technical and product experience compared to participating in internships. Furthermore, our current version of the frontend is already approaching perfection, and there are few new features to be added.

In the future, if we have new requirements that need to be implemented, we will create an issue for it. This information will not be directly notified to you, as we don't want it to be like assigning tasks. If you are willing to implement a specific issue, you can communicate with us there.

**Comment by OrkWard** [comment]
Thank you for your patient reply. However contribution is more like a kind of fun and learning experience...in that case I'll participate in my own pace

**Review by iamNCJ — APPROVED** [review]

**Comment by iamNCJ** [comment]
Really thank you for your great work! @OrkWard

**Comment by fish98** [comment]
❤️

**Pull request merged**
